[package]
name = "readings-probe"
version = "0.1.0"
authors = ["Mathieu Poumeyrol <kali@zoy.org>"]
edition = "2018"

[dependencies]
libc = "0.2.68"
num_cpus = "1.12.0"
thiserror = "1.0.13"
winapi = "0.3"
